name: Laravel CI/CD

on:
  push:
    branches:
      - main # Ganti jika kamu pakai branch lain

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          git config --global --add safe.directory /var/www/boardinaja
          cd /var/www/boardinaja/
          git pull origin main
          git status
